### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ashwinexe**
This PR adds the Code of Conduct for Hackerabad Community

### CODE REVIEW

**Review by vijay-jaisankar — COMMENTED** [review]
For this block:
```
Encouraged behaviour: 
* Supporting other's in help channels
* Using inclusive Language and pronouns
* Reporting an incident to the Team
```

General comments:
- (Very small ) grammar correction: 
> Supporting others in help channels
- It would be nice if you can add the contact details of the moderators (for example, the relevant discord channels)

**Review by ashwinexe — COMMENTED** [review]
fix: Add support contact and fix grammar

**Comment by ashwinexe** [comment]
> For this block:
> 
> ```
> Encouraged behaviour: 
> * Supporting other's in help channels
> * Using inclusive Language and pronouns
> * Reporting an incident to the Team
> ```
> 
> General comments:
> 
> * (Very small ) grammar correction:
> 
> > Supporting others in help channels
> 
> * It would be nice if you can add the contact details of the moderators (for example, the relevant discord channels)

Thanks for reviewing I have fixed the grammar and added the contacts.

**Comment by vijay-jaisankar** [comment]
Awesome, thanks!

**Pull request merged**
